### Counting annotated abfs and total abfs seeing which files my App Script failed to download

- 158 abfs are annotated in `4D...` excel sheet out of 794 in the shared Google Folder
- 29 out of 39 cells are labeled in the `List of Cells` excel sheet 

In [2]:
# Imports
import pandas as pd
import numpy as np
import re

In [15]:
def trace_filter_abf(array):
    pattern = r"\d{4}_\d{2}_\d{2}_\d{4}\.abf"
    filtered = [item for item in array if re.match(pattern+'.abf', str(item))]
    return np.array(filtered)

### Names of each annotation sheet

In [25]:
sheet_names_df = pd.read_csv('/Users/Haley/Desktop/Neuroscience Lab/Repository/murray-neuroscience-lab/Processed CSVs/sheet_names.csv', header=None)
sheet_names = sheet_names_df.iloc[:,0].values
print(len(sheet_names)==len(set(sheet_names)))
print(len(sheet_names))

sheet_names # names of each annotation sheet

True
39


array(['2012_04_25_cell1', '2012_04_25_cell3', '2012_04_27_cell1',
       '2012_06_22_cell3', '2012_06_25_cell3', '2012_06_29',
       '2012_08_01_cell1', '2012_08_01_cell3', '2012_08_07',
       '2012_08_31_cell1', '2012_08_31_cell2', '2012_08_31_cell3',
       '2012_08_31_cell4', '2012_10_04_cell2', '2012_12_03_cell1',
       '2012_12_04_cell1', '2012_12_04_cell2', '2012_12_05_cell1',
       '2012_12_05_cell3', '2012_12_05_cell4', '2012_12_06_cell1',
       '2012_12_06_cell2', '2012_12_06_cell3', '2012_12_06_cell4',
       '2012_12_06_cell5', '2012_12_06_cell6', '2013_03_20_cell1',
       '2013_03_21_cell1', '2013_03_21_cell2', '2013_03_21_cell3',
       '2013_03_21_cell4', '2013_03_21_cell5', '2013_03_22_cell1',
       '2013_03_22_cell2', '2013_03_22_cell3', '2013_03_22_cell4',
       '2013_03_22_cell5', '2013_03_22_cell6', '2012_10_04_cell1'],
      dtype=object)

### Each sheet is a different cell , so all traces in one sheet are the same cell type and fast/slow preferrring population

In [22]:
cell_types_df = pd.read_csv("/Users/Haley/Desktop/Neuroscience Lab/Repository/murray-neuroscience-lab/Excel processor/List of cells.csv")
cell_types_df = cell_types_df.dropna(how='all')
cell_types_df = cell_types_df.iloc[:,:4]
cell_types_df.reset_index(drop=True,inplace=True)
cell_types_df

Cell             Cell Type  Input Resistance  \
0   2013_03_21_cell5                   CaP             33.00   
1   2013_03_22_cell6                  vRoP             42.00   
2   2013_03_22_cell2                   CaP             43.64   
3   2012_08_31_cell2                  vRoP             44.77   
4   2012_08_31_cell1                   MiP             45.33   
5   2012_08_31_cell3                   MiP             46.67   
6   2013_03_21_cell4                   MiP             47.15   
7   2012_08_01_cell3                   MiP             49.99   
8   2013_03_22_cell1                   CaP             51.00   
9   2013_03_20_cell1                   MiP             51.10   
10  2013_03_21_cell1                   MiP             56.77   
11  2013_03_21_cell3                   MiP             60.10   
12  2013_03_22_cell3                   CaP             69.00   
13  2012_04_25_cell1                  vRoP             74.45   
14  2012_12_06_cell1                  vRoP            112.00   
15  2013_03_22_cell4                  dRoP            114.00   
16  2012_04_25_cell3                  vRoP            157.29   
17  2013_03_22_cell5                   dVS            112.85   
18        2012_06_29                  vSMN            177.00   
19        2012_08_07                  vSMN            219.00   
20  2012_08_31_cell4                  dSMN            242.57   
21  2012_12_05_cell1                  dSMN            264.97   
22  2012_08_01_cell1                  vSMN            287.00   
23  2012_10_04_cell2                  dSMN            340.01   
24  2012_12_04_cell1                  vSMN            393.00   
25  2012_12_05_cell4                 vSMN             440.84   
26  2012_12_05_cell3                  vSMN            815.69   
27  2012_12_03_cell1                  iSMN            830.00   
28  2012_12_06_cell4  iSMN (dorsal) muscle            861.90   

            Motoneuron  
0              primary  
1              primary  
2              primary  
3              primary  
4              primary  
5              primary  
6              primary  
7              primary  
8              primary  
9              primary  
10             primary  
11             primary  
12             primary  
13             primary  
14             primary  
15             primary  
16             primary  
17  Low Rin Secondary   
18  Low Rin Secondary   
19  Low Rin Secondary   
20  Low Rin Secondary   
21  Low Rin Secondary   
22  Low Rin Secondary   
23  Low Rin Secondary   
24  High Rin Secondary  
25  High Rin Secondary  
26  High Rin Secondary  
27  High Rin Secondary  
28  High Rin Secondary

In [30]:
labled_cells = cell_types_df["Cell"].to_numpy()

# There are 10 sheets that arent labled

In [36]:
# Define two lists
list1 = labled_cells
list2 = sheet_names

# Find extra elements in list1
extra_in_list1 = list(set(list1) - set(list2))

# Find extra elements in list2
extra_in_list2 = list(set(list2) - set(list1))

# Print the results
print("Extra elements in list1:", extra_in_list1)
print("Extra elements in list2:", extra_in_list2)
len(extra_in_list2)

Extra elements in list1: []
Extra elements in list2: ['2012_10_04_cell1', '2012_12_06_cell3', '2012_12_06_cell6', '2012_12_06_cell2', '2013_03_21_cell2', '2012_06_25_cell3', '2012_12_06_cell5', '2012_04_27_cell1', '2012_12_04_cell2', '2012_06_22_cell3']


10

### All abf files available in shared folder

In [5]:
abfs = pd.read_csv('/Users/Haley/Desktop/Neuroscience Lab/Repository/murray-neuroscience-lab/Excel processor/all_abf_files.csv',header=None)
abfs = abfs[0].to_numpy()
abfs 

array(['2013_03_22_0045.abf', '2013_03_22_0042.abf',
       '2013_03_22_0039.abf', ..., '2012_08_29_0009.abf',
       '2012_08_29_0016.abf', '2012_08_29_0018.abf'],
      shape=(1050,), dtype=object)

Check to see duplicates

In [6]:
pattern = r"\d{4}_\d{2}_\d{2}_\d{4}\.abf"

abfs = [f for f in abfs if re.fullmatch(pattern, f)]

print(len(abfs)) 
print(len(set(abfs)))


1047
794


All traces in each sheet are unique

In [7]:
all_trace_names = []
for sheet in sheet_names:
    file_path = "/Users/Haley/Desktop/Neuroscience Lab/Repository/murray-neuroscience-lab/Processed CSVs/"+ sheet + '.csv'
    df_filtered = pd.read_csv(file_path)
    trace_names = df_filtered["Trace name"].unique().tolist()
    all_trace_names.extend(trace_names)

print(len(all_trace_names)==len(set(all_trace_names)))
print(len(all_trace_names))
print(type(all_trace_names[0]))


True
158
<class 'str'>


Note: only 158 out of 794 abf files have annotations 

In [9]:
missing_abfs = pd.read_csv('/Users/Haley/Desktop/Neuroscience Lab/Repository/murray-neuroscience-lab/Excel processor/missing_files.csv',header=None)
missing_abfs = missing_abfs[0].to_numpy()
print(len(missing_abfs))


439


In [10]:
pattern = r"\d{4}_\d{2}_\d{2}_\d{4}\.abf"

missing_abfs = [f for f in missing_abfs if re.fullmatch(pattern, f)]

print(len(missing_abfs)==len(set(missing_abfs)))
print(len(missing_abfs))


True
436


Find which traces are missing in the downloaded folder:

In [12]:
missing_abfs_base = [name.replace(".abf", "") for name in missing_abfs]

matches_missing = [name for name in all_trace_names if name in missing_abfs_base]

print(f"{len(matches_missing)} matches found:")
print(matches_missing)


77 matches found:
['2012_04_25_0004', '2012_04_25_0005', '2012_04_25_0006', '2012_04_25_0000', '2012_04_25_0001', '2012_04_25_0002', '2012_04_25_0030', '2012_04_25_0031', '2012_04_25_0032', '2012_04_25_0033', '2012_04_25_0027', '2012_04_25_0028', '2012_04_25_0029', '2012_04_27_0003', '2012_04_27_0004', '2012_04_27_0005', '2012_04_27_0001', '2012_04_27_0002', '2012_04_27_0006', '2012_04_27_0007', '2012_06_22_0012', '2012_06_22_0014', '2012_06_25_0041', '2012_06_25_0042', '2012_06_29_0005', '2012_06_29_0006', '2012_06_29_0007', '2012_06_29_0001', '2012_06_29_0002', '2012_06_29_0003', '2012_08_31_0041', '2012_08_31_0042', '2012_08_31_0043', '2012_08_31_0038', '2012_08_31_0039', '2012_08_31_0037', '2012_10_04_0029', '2012_10_04_0030', '2012_10_04_0025', '2012_10_04_0026', '2012_10_04_0027', '2012_10_04_0023', '2012_10_04_0024', '2012_12_03_0002', '2012_12_04_0007', '2012_12_04_0008', '2012_12_04_0021', '2012_12_05_0013', '2012_12_05_0008', '2012_12_05_0004', '2012_12_05_0005', '2012_12_05_

AttributeError: 'list' object has no attribute 'to_csv'

In [13]:
matches_missing_df = pd.DataFrame(matches_missing, columns = ["Missing files"])
matches_missing_df.to_csv("matches_missing.csv", index=False)

Check to see that all the sheet traces have abf files

In [53]:
abfs_base = [name.replace(".abf", "") for name in abfs]

matches = [name for name in all_trace_names if name in abfs_base]

print(f"{len(matches)} matches found:")
print(matches)

157 matches found:
['2012_04_25_0004', '2012_04_25_0005', '2012_04_25_0006', '2012_04_25_0000', '2012_04_25_0001', '2012_04_25_0002', '2012_04_25_0030', '2012_04_25_0031', '2012_04_25_0032', '2012_04_25_0033', '2012_04_25_0027', '2012_04_25_0028', '2012_04_25_0029', '2012_04_27_0003', '2012_04_27_0004', '2012_04_27_0005', '2012_04_27_0001', '2012_04_27_0002', '2012_04_27_0006', '2012_04_27_0007', '2012_06_22_0012', '2012_06_22_0014', '2012_06_25_0041', '2012_06_25_0042', '2012_06_29_0005', '2012_06_29_0006', '2012_06_29_0007', '2012_06_29_0001', '2012_06_29_0002', '2012_06_29_0003', '2012_08_01_0009', '2012_08_01_0010', '2012_08_01_0011', '2012_08_01_0005', '2012_08_01_0006', '2012_08_01_0007', '2012_08_01_0008', '2012_08_01_0002', '2012_08_01_0003', '2012_08_01_0075', '2012_08_01_0076', '2012_08_01_0077', '2012_08_01_0078', '2012_08_01_0071', '2012_08_01_0072', '2012_08_01_0073', '2012_08_01_0074', '2012_08_01_0081', '2012_08_01_0082', '2012_08_01_0069', '2012_08_01_0070', '2012_08_07

In [ ]:
print(f"{len(matches)} matches and {len(matches)} annotated trace names")

print(all_trace_names)
print(matches)

['2012_04_25_0004', '2012_04_25_0005', '2012_04_25_0006', '2012_04_25_0000', '2012_04_25_0001', '2012_04_25_0002', '2012_04_25_0030', '2012_04_25_0031', '2012_04_25_0032', '2012_04_25_0033', '2012_04_25_0027', '2012_04_25_0028', '2012_04_25_0029', '2012_04_27_0003', '2012_04_27_0004', '2012_04_27_0005', '2012_04_27_0001', '2012_04_27_0002', '2012_04_27_0006', '2012_04_27_0007', '2012_06_22_0012', '2012_06_22_0014', '2012_06_25_0041', '2012_06_25_0042', '2012_06_29_0005', '2012_06_29_0006', '2012_06_29_0007', '2012_06_29_0001', '2012_06_29_0002', '2012_06_29_0003', '2012_08_01_0009', '2012_08_01_0010', '2012_08_01_0011', '2012_08_01_0005', '2012_08_01_0006', '2012_08_01_0007', '2012_08_01_0008', '2012_08_01_0002', '2012_08_01_0003', '2012_08_01_0075', '2012_08_01_0076', '2012_08_01_0077', '2012_08_01_0078', '2012_08_01_0071', '2012_08_01_0072', '2012_08_01_0073', '2012_08_01_0074', '2012_08_01_0081', '2012_08_01_0082', '2012_08_01_0069', '2012_08_01_0070', '2012_08_07_0019', '2012_08_07

In [58]:
# Define two lists
list1 = all_trace_names
list2 = matches

# Find extra elements in list1
extra_in_list1 = list(set(list1) - set(list2))

# Find extra elements in list2
extra_in_list2 = list(set(list2) - set(list1))

# Print the results
print("Extra elements in list1:", extra_in_list1)
print("Extra elements in list2:", extra_in_list2)


Extra elements in list1: ['2012_03_21_0027']
Extra elements in list2: []


['2012_03_21_0027'] in annotations files, but not in folder

In [59]:
trace_names_with_ext = [name + ".abf" for name in all_trace_names]

# Save to CSV
df = pd.DataFrame(trace_names_with_ext, columns=["filename"])
df.to_csv("abf_trace_names.csv", index=False)

In [11]:
all_trace_names

['2012_04_25_0004',
 '2012_04_25_0005',
 '2012_04_25_0006',
 '2012_04_25_0000',
 '2012_04_25_0001',
 '2012_04_25_0002',
 '2012_04_25_0030',
 '2012_04_25_0031',
 '2012_04_25_0032',
 '2012_04_25_0033',
 '2012_04_25_0027',
 '2012_04_25_0028',
 '2012_04_25_0029',
 '2012_04_27_0003',
 '2012_04_27_0004',
 '2012_04_27_0005',
 '2012_04_27_0001',
 '2012_04_27_0002',
 '2012_04_27_0006',
 '2012_04_27_0007',
 '2012_06_22_0012',
 '2012_06_22_0014',
 '2012_06_25_0041',
 '2012_06_25_0042',
 '2012_06_29_0005',
 '2012_06_29_0006',
 '2012_06_29_0007',
 '2012_06_29_0001',
 '2012_06_29_0002',
 '2012_06_29_0003',
 '2012_08_01_0009',
 '2012_08_01_0010',
 '2012_08_01_0011',
 '2012_08_01_0005',
 '2012_08_01_0006',
 '2012_08_01_0007',
 '2012_08_01_0008',
 '2012_08_01_0002',
 '2012_08_01_0003',
 '2012_08_01_0075',
 '2012_08_01_0076',
 '2012_08_01_0077',
 '2012_08_01_0078',
 '2012_08_01_0071',
 '2012_08_01_0072',
 '2012_08_01_0073',
 '2012_08_01_0074',
 '2012_08_01_0081',
 '2012_08_01_0082',
 '2012_08_01_0069',


In [ ]:
import pyabf

In [ ]:
file_path = ""
df = pd.read_csv(file_path)
df[["Trace name","Tags","Type"]] = df[["Trace name","Tags","Type"]].astype("string")
traces = df["Trace name"].unique().tolist()
abf = {}
for trace in trace_names:
    abfs[trace] = []
    file_path2 = "/Users/Haley/Downloads/.abf files annotated/" + trace + ".abf"
    abf = pyabf.ABF(file_path2)
    abfs[trace].append(abf)
    